#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
#

title: cjrequena
email: carlosjose.requena@gmail.com
description: >
  Carlos Requena, Software Architect @cjrequena. Writing about coding,
  microservices, distributed systems, performance optimisation
  and software architeture.
url: "http://cjrequena.github.io"
date_format: "%b %-d, %Y"
enable_mathjax: true
exclude: ["*.Rmd"]

# Build settings
markdown: kramdown
paginate: 5
gems:
  - jekyll-paginate
  - jekyll-feed

#      _____            _       __   __  ___         ___
#     / ___/____  _____(_)___ _/ /  /  |/  /__  ____/ (_)___ _
#     \__ \/ __ \/ ___/ / __ `/ /  / /|_/ / _ \/ __  / / __ `/
#    ___/ / /_/ / /__/ / /_/ / /  / /  / /  __/ /_/ / / /_/ /
#   /____/\____/\___/_/\__,_/_/  /_/  /_/\___/\__,_/_/\__,_/
#
#
show_social_icons: true
twitter_username: cjrequena
github_username:  cjrequena
disqus_shortname: cjrequena
google_analytics: UA-17092483-5


